apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJwcmVtZ293ZGEiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiZW1haWwiOiJwcmVtQGdtYWlsLmNvbSIsImF1dGgiOiJjSEpsYldkdmQyUmhPbkJoYzNOM2IzSmsifX19
kind: Secret
metadata:
  name: mydocker-secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: myimage
  imagePullSecrets:
    - name: mydocker-secret