apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv # from host-path-presistent-volume.yaml
  accessModes:
    - ReadWriteOnce
  stoargeClassName: standard
  resources:
    requests:
      storage: 1Gi