apiVersion: v1
kind: Service # service controls pods and not the deployments
metadata:
  name: backend-service
spec:
  selector:
    app: kub-second-app
  ports:
    - protocol: 'TCP'
      port: 3005 # expose
      targetPort: 8080 # of container
  type: LoadBalancer

