apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-a-deployment
    # run: service-a-deployment
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-deployment
  template:
    metadata:
      labels:
        app: service-a-deployment
    spec:
      containers:
      - image: registry.premgowda.in/instrumentation-service-a:latest
        name: service-a
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          limits: 
            memory: "256Mi"
            cpu: "250m"
        env:
          - name: OTEL_EXPORTER_JAEGER_HOST
            value: jaeger-agent.tracing.svc
      imagePullSecrets:
      - name: regcred