services:
  jaeger:
    image: jaegertracing/all-in-one:1.6.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
    container_name: jaeger
  service-a:
    image: registry.premgowda.in/instrumentation-service-a:latest
    ports:
      - 3001:3001
    environment:
      - OTEL_EXPORTER_JAEGER_HOST=jaeger
    depends_on: 
      - jaeger
    container_name: service-a
