apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-set
spec:
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - name: nginx-dm
        image: nginx
        ports:
        - containerPort: 80
