apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybackendapp
spec:
  selector:
    matchLabels:
      app: mybackendapp
  replicas: 2
  template:
    metadata:
      labels:
        app: mybackendapp
    spec:
      containers:
      - name: mybackend
        image: "docker.io/premgowda98/backend:latest"
        ports:
        - containerPort: 8501
        # imagePullPolicy: Always
        env:
        - name: PAYMENT_URL
          value: "mypaymentapp-service.default.svc.cluster.local:8502"
        resources:
          limits: 
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypaymentapp
spec:
  selector:
    matchLabels:
      app: mypaymentapp
  replicas: 2
  template:
    metadata:
      labels:
        app: mypaymentapp
    spec:
      containers:
      - name: mypayment
        image: "docker.io/premgowda98/payment:latest"
        ports:
        - containerPort: 8502
        # imagePullPolicy: Always
        env:
        - name: BACKEND_URL
          value: "mybackendapp-service.default.svc.cluster.local:8501"
        resources:
          limits: 
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: mybackendapp-service
spec:
  # type: LoadBalancer
  selector:
    app: mybackendapp
  ports:
  - name: "backend-port"
    port: 8501
    targetPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: mypaymentapp-service
spec:
  # type: LoadBalancer
  selector:
    app: mypaymentapp
  ports:
  - name: "payment-port"
    port: 8502
    targetPort: 8502